In [22]:
import numpy as np

In [23]:
def compute_homography(src_points, dst_points):
    # Check that there are at least 4 corresponding points
    assert src_points.shape[0] == dst_points.shape[0] and src_points.shape[0] >= 4
    
    A = []
    for i in range(src_points.shape[0]):
        x, y = src_points[i]
        u, v = dst_points[i]
        A.extend([
            [-x, -y, -1, 0, 0, 0, u*x, u*y, u],
            [0, 0, 0, -x, -y, -1, v*x, v*y, v]
        ])
    A = np.array(A)
    
    _, _, V = np.linalg.svd(A)
    H = V[-1].reshape(3, 3)
    return H

In [24]:
def warp_func(H,coords):
    x, y = coords
    xy_homogeneous = np.array([x, y, 1])
    uvw = np.dot(H, xy_homogeneous)
    return [uvw[1] / uvw[2], uvw[0] / uvw[2]]

In [33]:
src_points = np.array([[10, 10], [10, 50], [50, 50], [50, 10]])
dst_points = np.array([[20, 20], [10, 60], [50, 60], [60, 20]])
H = compute_homography(src_points, dst_points)
print(H)

[[ 6.20995244e-02 -1.55248811e-02  7.76244055e-01]
 [ 6.34794574e-16  6.20995244e-02  6.20995244e-01]
 [-2.31330642e-16  1.29491841e-16  6.20995244e-02]]


In [31]:
for x,y in src_points:
    print(warp_func(H,(x,y)))

[19.999999999999687, 19.999999999999975]
[59.99999999999173, 9.999999999997053]
[60.00000000000108, 49.999999999998956]
[20.000000000003073, 60.00000000000669]
